name: release
on:
  push:
    tags:
      - '*'

env:
  IMAGE_NAME: ${{ github.event.repository.name }}
  VERSION: '7.3.0'
  SHA256: 'e5b209a89766f3cceea058448fbc03ac45d12dd2ebb3df1115a7c9a7956ee0e5'

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up cosign
        uses: sigstore/cosign-installer@main

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: thojkooi
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: thojkooi
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify base image
        run: |
          cosign dockerfile verify -base-image-only -key ./build/cosign-allowed-dependencies.pub Dockerfile

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          args: release --skip-announce --skip-validate --snapshot --skip-validate --rm-dist
